# Generated by Django 4.2.5 on 2023-09-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_Session', models.CharField(default='2003/2024', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Name Of Academic Session',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(default='0001', max_length=100)),
                ('program_type', models.CharField(choices=[('phd', 'PHD'), ('masters', 'Masters'), ('full_time', 'Full Time'), ('part_time', 'Part Time'), ('diploma', 'Diploma'), ('predegree', 'Pre Degree'), ('default', 'Full Time')], default='Full Time', max_length=50)),
                ('matrix_No', models.CharField(default='2003/csc-0001', max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=100)),
                ('duration', models.CharField(default='5', max_length=100)),
                ('admission_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('accepted', 'Admitted and Accepted'), ('rejected', 'Admitted but Rejected'), ('denied', 'Not Admitted'), ('differed', 'Amitted But Defered'), ('default', 'accepted')], default='Full Time', max_length=50)),
                ('academic_Session', models.ForeignKey(default='2003/2024', on_delete=django.db.models.deletion.CASCADE, to='studentmgt.academicsession')),
            ],
            options={
                'verbose_name_plural': 'Admission List',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_Code', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Course Code',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_Title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Name Of Department',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(default='1', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Name Of Faculty',
            },
        ),
        migrations.CreateModel(
            name='LocalGovernment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Local Government Origin',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Nationality',
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted_class', models.CharField(default='1', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Name Of Start Class',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'State Of Origin',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_Name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Name Of Village',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=200)),
                ('sure_Name', models.CharField(max_length=200)),
                ('other_Name', models.CharField(max_length=200)),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('phone_No', models.CharField(default='+234', max_length=200, unique=True)),
                ('email', models.CharField(default='email@example.com', max_length=200, unique=True)),
                ('profile_pic', models.ImageField(blank=True, default='avatar', upload_to='profile_pic/Student/')),
                ('home_Address', models.CharField(max_length=40)),
                ('mother_Maiden_name', models.CharField(max_length=200)),
                ('local_Government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmgt.localgovernment')),
                ('matrix_No', models.OneToOneField(default='2003/csc-0001', on_delete=django.db.models.deletion.CASCADE, to='studentmgt.admission')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmgt.nationality')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmgt.state')),
                ('village_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmgt.village')),
            ],
            options={
                'verbose_name_plural': 'Students Personal Information',
            },
        ),
        migrations.CreateModel(
            name='CreateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_Question', models.CharField(max_length=200)),
                ('option_A', models.CharField(max_length=200)),
                ('option_B', models.CharField(max_length=200)),
                ('option_C', models.CharField(max_length=200)),
                ('option_D', models.CharField(max_length=200)),
                ('marks', models.CharField(max_length=200)),
                ('correct_Answer', models.CharField(max_length=200)),
                ('course_Code', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='studentmgt.code')),
                ('course_title', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='studentmgt.course')),
                ('name_of_Department', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='studentmgt.department')),
            ],
            options={
                'verbose_name_plural': 'Question Bank',
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='admitted_class',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='studentmgt.placement'),
        ),
        migrations.AddField(
            model_name='admission',
            name='department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='studentmgt.department'),
        ),
        migrations.AddField(
            model_name='admission',
            name='faculty',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='studentmgt.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='admission',
            unique_together={('matrix_No', 'program_type')},
        ),
    ]
