# Generated by Django 4.2.5 on 2023-09-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmgt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='program_id',
        ),
        migrations.AddField(
            model_name='admission',
            name='program_Id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
